# Generates everything derived from homelab.env + the enabled stacks.
# Sourced by lab and install.sh (after common.sh). Safe to run any time:
# it never overwrites an existing secret or anything under data/.

HOMEPAGE_GROUPS=(Infrastructure Photos Documents AI Files Backups Home Finance)

gen_secret() { openssl rand -hex 24; }

# stack_env <stack>: create stacks/<s>/.env from .env.example once, fill
# generated secrets that are still empty, sync the keys we manage.
stack_env() {
  local s="$1" dir="$STACKS_DIR/$1" env k
  env="$dir/.env"
  if [[ ! -f "$env" ]]; then
    if [[ -f "$dir/.env.example" ]]; then cp "$dir/.env.example" "$env"; else : > "$env"; fi
    chmod 600 "$env"
  fi
  for k in $(stack_meta "$s" SECRETS); do
    [[ -n "$(env_get "$env" "$k")" ]] || env_set "$env" "$k" "$(gen_secret)"
  done
  case "$s" in
    caddy)
      # Glances' route logs in for the browser (stacks/glances/caddy.conf).
      if is_enabled glances; then
        stack_env glances
        env_set "$env" GLANCES_BASIC_AUTH \
          "$(printf 'glances:%s' "$(env_get "$STACKS_DIR/glances/.env" GLANCES_PASSWORD)" | base64 -w0)"
      fi ;;
    ntfy)
      # ntfy's own formats: a tk_ token, and a password typed on a phone.
      [[ -n "$(env_get "$env" NTFY_PUBLISH_TOKEN)" ]] || env_set "$env" NTFY_PUBLISH_TOKEN \
        "tk_$(openssl rand -hex 15 | cut -c1-29)"
      [[ -n "$(env_get "$env" NTFY_PHONE_PASSWORD)" ]] || env_set "$env" NTFY_PHONE_PASSWORD \
        "$(openssl rand -hex 10)" ;;
    homepage)
      # The Glances widgets log in with Glances' generated password.
      if is_enabled glances; then
        stack_env glances
        env_set "$env" HOMEPAGE_VAR_GLANCES_PASSWORD \
          "$(env_get "$STACKS_DIR/glances/.env" GLANCES_PASSWORD)"
      fi ;;
    immich)
      env_set "$env" UPLOAD_LOCATION "$PHOTOS_DIR"
      env_set "$env" TZ "$TZ" ;;
    paperless-ngx)
      # The AI script and the Actual wrapper share one API key.
      if is_enabled actual-budget; then
        stack_env actual-budget
        env_set "$env" ACTUAL_HTTP_API_KEY \
          "$(env_get "$STACKS_DIR/actual-budget/.env" ACTUAL_HTTP_API_KEY)"
        k="$(env_get "$STACKS_DIR/actual-budget/.env" ACTUAL_BUDGET_SYNC_ID)"
        [[ -n "$k" ]] && env_set "$env" ACTUAL_BUDGET_SYNC_ID "$k"
      fi ;;
  esac
  return 0
}

# stack_dirs <stack>: create the host folders a stack mounts.
stack_dirs() {
  local d path
  for d in $(stack_meta "$1" DIRS); do
    if [[ "$d" =~ ^[A-Z_][A-Z0-9_]*$ ]]; then path="${!d:-}"; else path="$(render_template <<<"$d")"; fi
    [[ -n "$path" ]] || continue
    mkdir -p "$path" 2>/dev/null || warn "could not create $path (create it yourself)"
  done
  return 0
}

render_caddy() {
  local out="$RENDER_DIR/caddy" s
  rm -rf "$out.tmp"; mkdir -p "$out.tmp/sites" "$out.tmp/extra"
  cp "$STACKS_DIR/caddy/Caddyfile.base" "$out.tmp/Caddyfile"
  case "$TLS_MODE" in
    cloudflare) printf 'tls {\n\tdns cloudflare {env.CF_API_TOKEN}\n}\n' > "$out.tmp/tls.conf" ;;
    internal)   printf 'tls internal\n' > "$out.tmp/tls.conf" ;;
    *) die "TLS_MODE must be cloudflare or internal, not '$TLS_MODE'" ;;
  esac
  for s in $(enabled_stacks); do
    [[ -f "$STACKS_DIR/$s/caddy.conf" ]] && cp "$STACKS_DIR/$s/caddy.conf" "$out.tmp/sites/$s.conf"
  done
  cp "$ROOT/extras/topology/caddy.conf" "$out.tmp/sites/zz-map.conf"
  if [[ -n "${HA_URL:-}" ]]; then
    render_template < "$ROOT/extras/homeassistant/caddy.conf" > "$out.tmp/sites/homeassistant.conf"
  fi
  # Private overlay: extra routes in the wildcard site, extra top-level sites.
  local f
  for f in "${LOCAL_DIR:-/nonexistent}"/caddy/sites/*.conf; do
    [[ -f "$f" ]] && render_template < "$f" > "$out.tmp/sites/local-$(basename "$f")"
  done
  for f in "${LOCAL_DIR:-/nonexistent}"/caddy/*.caddy; do
    [[ -f "$f" ]] && render_template < "$f" > "$out.tmp/extra/$(basename "$f")"
  done
  # Swap the whole directory's contents but keep the directory itself: the
  # running container has it bind-mounted.
  mkdir -p "$out"
  rm -rf "${out:?}"/*
  cp -r "$out.tmp"/. "$out"/
  rm -rf "$out.tmp"
}

render_topology() {
  local out="$RENDER_DIR/topology"
  mkdir -p "$out"
  cp "$ROOT/extras/topology/index.html" "$out/index.html"
  # Your own map: LOCAL_DIR/topology.md, or ./topology.md (gitignored);
  # otherwise the example.
  if [[ -f "${LOCAL_DIR:-/nonexistent}/topology.md" ]]; then cp "$LOCAL_DIR/topology.md" "$out/topology.md"
  elif [[ -f "$ROOT/topology.md" ]]; then cp "$ROOT/topology.md" "$out/topology.md"
  else cp "$ROOT/extras/topology/topology.example.md" "$out/topology.md"; fi
}

# homepage_items <file>: a fragment, indented to sit under its group.
homepage_items() { render_template < "$1" | sed 's/^/    /'; }

render_homepage() {
  local cfg="$STACKS_DIR/homepage/config" g s f body out
  mkdir -p "$cfg"
  render_template < "$STACKS_DIR/homepage/settings.yaml" > "$cfg/settings.yaml"
  cp "$STACKS_DIR/homepage/custom.css" "$cfg/custom.css"

  out="# Generated by ./lab render from each stack's homepage.yaml. Edit those."$'\n'
  for g in "${HOMEPAGE_GROUPS[@]}"; do
    body=""
    for s in $(enabled_stacks); do
      [[ "$(stack_meta "$s" GROUP)" == "$g" ]] || continue
      f="$STACKS_DIR/$s/homepage.yaml"
      [[ -f "$f" ]] && body+="$(homepage_items "$f")"$'\n'
      f="$STACKS_DIR/$s/homepage.gpu.yaml"
      [[ -f "$f" ]] && is_yes "${GPU:-no}" && body+="$(homepage_items "$f")"$'\n'
    done
    if [[ "$g" == Infrastructure ]]; then
      body+="$(homepage_items "$ROOT/extras/topology/homepage.yaml")"$'\n'
    fi
    if [[ "$g" == Home && -n "${HA_URL:-}" ]]; then
      if [[ -n "$(env_get "$STACKS_DIR/homepage/.env" HOMEPAGE_VAR_HA_TOKEN)" ]]; then
        body+="$(homepage_items "$ROOT/extras/homeassistant/homepage.widget.yaml")"$'\n'
      else
        body+="$(homepage_items "$ROOT/extras/homeassistant/homepage.yaml")"$'\n'
      fi
    fi
    f="${LOCAL_DIR:-/nonexistent}/homepage/$g.yaml"
    [[ -f "$f" ]] && body+="$(homepage_items "$f")"$'\n'
    [[ -n "$body" ]] && out+="- $g:"$'\n'"$body"
  done
  # Overlay groups that aren't one of the standard ones go last.
  for f in "${LOCAL_DIR:-/nonexistent}"/homepage/*.yaml; do
    [[ -f "$f" ]] || continue
    g="$(basename "$f" .yaml)"
    [[ " ${HOMEPAGE_GROUPS[*]} " == *" $g "* ]] && continue
    out+="- $g:"$'\n'"$(homepage_items "$f")"$'\n'
  done
  printf '%s' "$out" > "$cfg/services.yaml"

  {
    echo "# Generated by ./lab render."
    if [[ -n "${WEATHER_LAT:-}" ]]; then
      cat <<EOF
- openmeteo:
    label: ${WEATHER_LABEL:-Weather}
    latitude: ${WEATHER_LAT}
    longitude: ${WEATHER_LON}
    timezone: ${TZ}
    units: metric
    cache: 5
EOF
    fi
    cat <<'EOF'
- datetime:
    text_size: md
    format:
      dateStyle: long
      timeStyle: short
EOF
  } > "$cfg/widgets.yaml"
}

render_cloudflared() {
  local out="$RENDER_DIR/cloudflared" s pub port
  rm -rf "$out"
  [[ -n "${PUBLIC_DOMAIN:-}" ]] || return 0
  mkdir -p "$out"
  {
    echo "# Generated by ./lab render. Install with: ./install.sh --public"
    echo "# (cloudflared only reads /etc/cloudflared/config.yml.)"
    echo "tunnel: ${CLOUDFLARED_TUNNEL:-CHANGE-ME}"
    echo "credentials-file: /etc/cloudflared/${CLOUDFLARED_TUNNEL:-CHANGE-ME}.json"
    echo "ingress:"
    for s in $(enabled_stacks); do
      pub="$(stack_meta "$s" PUBLIC)"; port="$(stack_meta "$s" PUBLIC_PORT)"
      [[ -n "$pub" && -n "$port" ]] || continue
      echo "  - hostname: $pub.$PUBLIC_DOMAIN"
      echo "    service: http://127.0.0.1:$port"
    done
    # Private overlay: extra ingress entries, same "  - hostname:" format.
    [[ -f "${LOCAL_DIR:-/nonexistent}/cloudflared.yml" ]] && render_template < "$LOCAL_DIR/cloudflared.yml"
    echo "  - service: http_status:404"
  } > "$out/config.yml"
}

render_backup() {
  local out="$RENDER_DIR/backup" f unit
  rm -rf "$out"
  [[ "${BACKUP_TARGET:-none}" != none ]] || return 0
  mkdir -p "$out"
  for f in "$ROOT"/extras/backup/units/*; do
    render_template < "$f" > "$out/$(basename "$f")"
  done
  unit="$(systemd-escape -p "$BACKUP_DIR")"
  if [[ "$BACKUP_TARGET" == smb ]]; then
    mv "$out/backup.mount" "$out/$unit.mount"
    mv "$out/backup.automount" "$out/$unit.automount"
    sed -i "s/@MOUNT_UNIT@/$unit.mount/g" "$out"/*.service
  else
    rm -f "$out/backup.mount" "$out/backup.automount"
    sed -i '/@MOUNT_UNIT@/d' "$out"/*.service
  fi
}

# render_all: the whole thing. Needs homelab.env loaded.
render_all() {
  local s
  [[ -n "${DOMAIN:-}" ]] || die "DOMAIN is not set in homelab.env"
  mkdir -p "$RENDER_DIR"
  is_enabled caddy || STACKS="caddy ${STACKS:-}"
  for s in $(enabled_stacks); do
    stack_env "$s"
    stack_dirs "$s"
  done
  [[ -f "$STACKS_DIR/caddy/.env" ]] || stack_env caddy
  render_caddy
  render_topology
  is_enabled homepage && render_homepage
  render_cloudflared
  render_backup
  return 0
}
