DESCRIPTION="Budgeting (envelope style), with an HTTP API wrapper"
GROUP=Finance
HOST=budget
SECRETS="ACTUAL_HTTP_API_KEY"
PROFILES="standard full"
OVERLAYS="http-api.yml:?ACTUAL_SERVER_PASSWORD"
CONTAINERS="actual"
RAM_GB=0.5
DISK_GB=1
